name: Build geoip files

on:
  workflow_dispatch:
  schedule:
    - cron: "20 23 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
      - "config-example.json"
      - "LICENSE"
      - "README.md"

env: 
  TZ: Asia/Hong_Kong

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Workflow runs delete
        uses: InfraWay/delete-workflow-runs@v2.1.2
        with:
          token: ${{ secrets.xyysjd_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3

      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod

      - name: Append more CIDRs
        run: |
          mkdir -p data
          curl -sSL https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Surge/BiliBili/BiliBili_Resolve.list | grep IP-CIDR, | sed 's/IP-CIDR,//g' > data/bilibili
          curl -sSL https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt | grep -v '#' >> data/cn
          curl -sSL https://www.gstatic.com/ipranges/goog.json | jq --raw-output '.prefixes[].ipv4Prefix,.prefixes[].ipv6Prefix | select(. != null)' >> data/google
          curl -sSL https://www.gstatic.com/ipranges/cloud.json | jq --raw-output '.prefixes[].ipv4Prefix,.prefixes[].ipv6Prefix | select(. != null)' >> data/google
          curl -sSL https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Surge/Netflix/Netflix_Resolve.list | grep -E "IP-CIDR,|IP-CIDR6," | sed 's/IP-CIDR,//g; s/IP-CIDR6,//g' > data/netflix
          curl -sSL https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Surge/WeChat/WeChat_Resolve.list | grep -E "IP-CIDR,|IP-CIDR6," | sed 's/IP-CIDR,//g; s/IP-CIDR6,//g' > data/wechat
          curl -sSL https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Surge/Twitter/Twitter_Resolve.list | grep -E "IP-CIDR,|IP-CIDR6," | sed 's/IP-CIDR,//g; s/IP-CIDR6,//g' > data/twitter
          curl -sSL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/YouTube/YouTube_Resolve.list | grep -E "IP-CIDR,|IP-CIDR6," | sed 's/IP-CIDR,//g; s/IP-CIDR6,//g' > data/youtube
      - name: Build geoip files
        run: |
          go run ./

      - name: Verify mmdb files
        if: success()
        run: |
          cd ./output/maxmind || exit 1
          go install github.com/maxmind/mmdbverify@main
          for name in $(ls *.mmdb); do
            $(go env GOPATH)/bin/mmdbverify -file ${name}
          done

      - name: Checkout Geo Repo
        uses: actions/checkout@v4
        with:
          repository: d2184/geo
          path: geo

      - name: Convert to db and metadb files
        run: |
          cd geo && go install -trimpath -ldflags="-s -w -buildid=" ./cmd/geo && cd ..
          
          mkdir -p publish
          geo convert ip -i v2ray -o sing -f ./publish/geoip-lite.db ./output/dat/geoip-lite.dat
          geo convert ip -i v2ray -o meta -f ./publish/geoip-lite.metadb ./output/dat/geoip-lite.dat
          geo convert ip -i v2ray -o sing -f ./publish/geoip.db ./output/dat/geoip.dat
          geo convert ip -i v2ray -o meta -f ./publish/geoip.metadb ./output/dat/geoip.dat

      - name: Move files to publish directory
        if: success()
        run: |
          mv -f ./output/dat/*.dat ./output/maxmind/*.mmdb ./publish/

      - name: Git push files to "release" branch
        run: |
          cd publish || exit 1
          git init --initial-branch=release
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "Last Updated $(date '+%Y-%m-%d %H:%M:%S')"
          git remote add geoip "https://${{ github.actor }}:${{ secrets.xyysjd_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u geoip release
